# Select image from https://hub.docker.com/r/_/php/
image: php:7.2

services:
    - mysql:5.5

before_script:
    # Install dependencies
    - bash ci/docker_install.sh > /dev/null
    # Install Xdebug
    - pecl install xdebug
    - docker-php-ext-enable xdebug
    #MySQL stuff
    #- mysql -e 'CREATE DATABASE test;'
    #- mysql -u root --password='hello' test < ./test_dump.sql
    #- mysql -e 'USE test; SELECT * FROM TEST;'
    
mysql_build:
  variables:
    MYSQL_DATABASE: hello_world_test
    MYSQL_ROOT_PASSWORD: mysql
  services:
  - mysql
  image: mysql
  before_script:
  - mysql --version
  script:
  - echo "SELECT 'OK';" | mysql --user=root --password="${MYSQL_ROOT_PASSWORD}" --host=mysql "${MYSQL_DATABASE}"
  - mysql -u root --password='mysql' --host=mysql hello_world_test < ./test_dump.sql

test:app:
  script:
    - phpunit --configuration phpunit_myapp.xml --coverage-text --colors=never
    - phpunit --version
  coverage: '/^\s*Lines:\s*\d+.\d+\%/'