# Select image from https://hub.docker.com/r/_/php/
image: php:7.2

before_script:
# Install dependencies
- bash ci/docker_install.sh > /dev/null
# Install Xdebug
- pecl install xdebug
- docker-php-ext-enable xdebug

test:app:
  script:
  - phpunit --configuration phpunit_myapp.xml
#  - php ./tests --coverage-text --colors=never
  - phpunit --dump-xdebug-filter xdebug-filter.php
  - phpunit --prepend xdebug-filter.php --coverage-html ./

  coverage: '/^\s*Lines:\s*\d+.\d+\%/'
