stages:
    - build
    - test
    - deploy

job 1:
    stage: build
    script: echo "Building"
    
job 2: 
    stage: test
    script: echo "Testing"
    
job 3:
    stage: deploy
    script: echo "Deploying"